name: JupyterViz
version: 1.2.0
date: 2018-10-28
description: |
    Jupyter Notebook Visualization Tools

authors:
    - name: Nathan Carter
      url: http://nathancarter.github.io

maintainers:
    - name: Nathan Carter
      url: http://nathancarter.github.io

GAP: ">= 4.9"

needed-pkgs:
    - name: "JupyterKernel"
      version: "0.99999"
      url: "http://gap-packages.github.io/JupyterKernel/"
    - name: "json"
      version: "2.0.0"
      url: "https://gap-packages.github.io/json/"
    - name: "GAPDoc"
      version: "1.3"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://nathancarter.github.io/jupyterviz
readme: README.md
packageinfo: https://nathancarter.github.io/jupyterviz/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/nathancarter/jupyterviz/releases/download/v1.2.0/jupyterviz-1.2.0.tar.gz

abstract: |
    The <span class="pkgname">JupyterViz</span> package    is intended for use in Jupyter Notebooks running    <span class="pkgname">GAP</span> kernels.     It adds visualization tools for use in such notebooks, such as    charts and graphs.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Jupyter Notebook, visualization, graph, plot, chart, JavaScript.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Car18</span>]   <b class='BibAuthor'>Carter, N.</b>,
     <i class='BibTitle'>JupyterViz, Jupyter Notebook Visualization Tools,
             Version 1.2.0</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://nathancarter.github.io/jupyterviz">https://nathancarter.github.io/jupyterviz</a></span>.
    </p>
    

bibtex: |
    @misc{ JupyterViz1.2.0,
      author =           {Carter, N.},
      title =            {{JupyterViz},  Jupyter  Notebook  Visualization Tools,
                          {V}ersion 1.2.0},
      month =            {Oct},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href      {https://nathancarter.github.io/jupyterviz}
                          {\texttt{https://nathancarter.github.io/}\discretionary
                          {}{}{}\texttt{jupyterviz}}},
      keywords =         {Jupyter  Notebook;  visualization; graph; plot; chart;
                          JavaScript},
      printedkey =       {Car18}
    }

